# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-17 19:38
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import webapps.buildinginfos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bemoss_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingInfo',
            fields=[
                ('building', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('zip_code', models.TextField()),
                ('description', models.TextField()),
                ('building_settings', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bemoss_accounts.BemossAccount')),
            ],
        ),
        migrations.CreateModel(
            name='BuildingMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bmap_file_location', models.ImageField(upload_to=webapps.buildinginfos.models.get_file_path)),
            ],
            options={
                'db_table': 'building_map',
            },
        ),
        migrations.CreateModel(
            name='GlobalSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heat_setpoint', models.IntegerField(blank=True, null=True)),
                ('cool_setpoint', models.IntegerField(blank=True, null=True)),
                ('illuminance', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'db_table': 'global_zone_setting',
            },
        ),
        migrations.CreateModel(
            name='IOTGateway',
            fields=[
                ('gateway', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('gateway_name', models.TextField()),
                ('date_attached', models.DateTimeField()),
                ('gateway_settings', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bemoss_accounts.BemossAccount')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildinginfos.BuildingInfo')),
            ],
        ),
        migrations.CreateModel(
            name='ZoneInfo',
            fields=[
                ('zone_id', models.AutoField(primary_key=True, serialize=False)),
                ('zone_nickname', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('zone_settings', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildinginfos.BuildingInfo')),
            ],
            options={
                'db_table': 'building_zone',
            },
        ),
        migrations.AddField(
            model_name='globalsetting',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildinginfos.ZoneInfo'),
        ),
    ]
