# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-05 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildinginfos', '0002_auto_20170718_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildinginfo',
            name='building',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
