# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-05 17:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildinginfos', '0003_auto_20170905_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buildinginfo',
            old_name='building',
            new_name='building_id',
        ),
    ]
