# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-14 23:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildinginfos', '0005_iotgateway_status'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='iotgateway',
            table='iot_gateway',
        ),
    ]
