# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-17 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BemossAccount',
            fields=[
                ('account', models.TextField(primary_key=True, serialize=False)),
                ('account_name', models.TextField()),
                ('description', models.TextField()),
                ('device_limit', models.IntegerField()),
                ('owner_reg_token', models.UUIDField()),
            ],
            options={
                'db_table': 'bemoss_account',
            },
        ),
        migrations.CreateModel(
            name='BemossToken',
            fields=[
                ('token', models.UUIDField(primary_key=True, serialize=False)),
                ('expiration_date', models.DateTimeField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bemoss_accounts.BemossAccount')),
                ('auth_user_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
            options={
                'db_table': 'bemoss_token',
            },
        ),
    ]
