# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-17 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildinginfos', '0001_initial'),
        ('deviceinfos', '0001_initial'),
        ('bemoss_applications', '0001_initial'),
        ('bemoss_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bemosstoken',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buildinginfos.BuildingInfo'),
        ),
        migrations.AddField(
            model_name='bemosstoken',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buildinginfos.ZoneInfo'),
        ),
        migrations.AddField(
            model_name='bemossaccount',
            name='applications_allowed',
            field=models.ManyToManyField(to='bemoss_applications.ApplicationRegistered'),
        ),
        migrations.AddField(
            model_name='bemossaccount',
            name='device_type_allowed',
            field=models.ManyToManyField(to='deviceinfos.DeviceType'),
        ),
    ]
