# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-05 17:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bemoss_accounts', '0002_auto_20170717_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bemossaccount',
            old_name='account',
            new_name='account_id',
        ),
    ]
