# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-13 19:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bemoss_accounts', '0003_auto_20170905_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bemossaccount',
            name='owner_reg_token',
        ),
    ]
