# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-15 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bemoss_accounts', '0004_remove_bemossaccount_owner_reg_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='bemosstoken',
            name='email',
            field=models.EmailField(default='aribemoss@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
