# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-11 15:39
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deviceinfos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicemetadata',
            name='factory_id',
        ),
        migrations.RemoveField(
            model_name='devicemetadata',
            name='max_range',
        ),
        migrations.RemoveField(
            model_name='devicemetadata',
            name='min_range',
        ),
        migrations.RemoveField(
            model_name='devicemetadata',
            name='password',
        ),
        migrations.RemoveField(
            model_name='devicemetadata',
            name='username',
        ),
        migrations.AddField(
            model_name='devicemetadata',
            name='config',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='devicemetadata',
            name='mac_address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
