# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-05 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deviceinfos', '0002_auto_20170811_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemetadata',
            name='building',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='buildinginfos.BuildingInfo'),
            preserve_default=False,
        ),
    ]
