# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-15 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildinginfos', '0006_auto_20170914_2305'),
        ('deviceinfos', '0003_auto_20170905_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemetadata',
            name='gateway_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buildinginfos.IOTGateway'),
        ),
    ]
