# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-15 17:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deviceinfos', '0004_devicemetadata_gateway_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicemetadata',
            old_name='gateway_id',
            new_name='gateway',
        ),
    ]
