# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-27 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deviceinfos', '0005_auto_20170915_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='supporteddevices',
            name='support_oauth',
            field=models.BooleanField(default=False),
        ),
    ]
