# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-09 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bemoss_accounts', '0005_bemosstoken_email'),
        ('deviceinfos', '0007_supporteddevices_built_in_schedule_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemetadata',
            name='account',
            field=models.ForeignKey(default='LabContract1', on_delete=django.db.models.deletion.CASCADE, to='bemoss_accounts.BemossAccount'),
            preserve_default=False,
        ),
    ]
