# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-05 21:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bemoss_applications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationregistered',
            old_name='app_folder',
            new_name='app_agent',
        ),
    ]
