# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-30 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicedata',
            name='last_update_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
