# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-09 15:25
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_devicedata_last_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicedata',
            name='locked_variables',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
